# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb",
         "double_it": "define_a_function.ipynb",
         "halve_it": "define_a_function.ipynb"}

modules = ["core.py",
           "define_a.py"]

doc_url = "https://Iain-S.github.io/wailing_gecko/"

git_url = "https://github.com/Iain-S/wailing_gecko/tree/main/"

def custom_doc_links(name): return None
