# AUTOGENERATED! DO NOT EDIT! File to edit: define_a_function.ipynb (unless otherwise specified).

__all__ = ['double_it', 'halve_it']

# Cell
def double_it(it):
    return it * 2

# export
def halve_it(it):
    return it / 2